services:
    thinframe.twig.views_path_mapper:
        class: 'ThinFrame\Twig\ViewPathMapper'

    thinframe.twig.loader:
        class: 'ThinFrame\Twig\TemplateLoader'
        arguments: ['@thinframe.twig.views_path_mapper']

    thinframe.twig.environment:
        class: 'Twig_Environment'
        arguments: ['@thinframe.twig.loader',{auto_reload: true,cache: 'app/cache/twig'}]

    thinframe.twig.listeners.view:
        class: 'ThinFrame\Twig\Listeners\ViewListener'
        arguments: ['@thinframe.twig.environment', '@thinframe.twig.views_path_mapper','@thinframe.annotations.collector']
        tags:
          - {name: 'thinframe.events.listener'}

    thinframe.twig.configuration:
        class: 'ThinFrame\Twig\Configuration'

    thinframe.twig.listeners.error_pages:
        class: 'ThinFrame\Twig\Listeners\ErrorPageListener'
        tags:
          - {name: 'thinframe.events.listener'}
        arguments: ['@thinframe.twig.configuration','@thinframe.twig.environment']