parameters:
    twig.cache_dir: '%karma.paths.root%/app/cache/twig'
services:
    twig.view_mapper:
        class: 'ThinFrame\Twig\ViewMapper'

    twig.loader:
        class: 'ThinFrame\Twig\TemplateLoader'
        arguments: ['@twig.view_mapper']

    twig.environment:
        class: 'Twig_Environment'
        arguments: ['@twig.loader',{auto_reload: true, cache: '%twig.cache_dir%'}]